Requirement already satisfied: google-generativeai in ./.venv_VV/lib/python3.12/site-packages (0.8.2)
Collecting google-generativeai
  Using cached google_generativeai-0.8.3-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: google-ai-generativelanguage==0.6.10 in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (0.6.10)
Requirement already satisfied: google-api-core in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (2.24.0)
Requirement already satisfied: google-api-python-client in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (2.154.0)
Requirement already satisfied: google-auth>=2.15.0 in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (2.36.0)
Requirement already satisfied: protobuf in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (5.29.1)
Requirement already satisfied: pydantic in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (2.9.2)
Requirement already satisfied: tqdm in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in ./.venv_VV/lib/python3.12/site-packages (from google-generativeai) (4.12.2)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in ./.venv_VV/lib/python3.12/site-packages (from google-ai-generativelanguage==0.6.10->google-generativeai) (1.25.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in ./.venv_VV/lib/python3.12/site-packages (from google-api-core->google-generativeai) (1.66.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in ./.venv_VV/lib/python3.12/site-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.venv_VV/lib/python3.12/site-packages (from google-auth>=2.15.0->google-generativeai) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.venv_VV/lib/python3.12/site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in ./.venv_VV/lib/python3.12/site-packages (from google-auth>=2.15.0->google-generativeai) (4.9)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in ./.venv_VV/lib/python3.12/site-packages (from google-api-python-client->google-generativeai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in ./.venv_VV/lib/python3.12/site-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in ./.venv_VV/lib/python3.12/site-packages (from google-api-python-client->google-generativeai) (4.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv_VV/lib/python3.12/site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in ./.venv_VV/lib/python3.12/site-packages (from pydantic->google-generativeai) (2.23.4)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in ./.venv_VV/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.10->google-generativeai) (1.68.1)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in ./.venv_VV/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.10->google-generativeai) (1.68.1)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./.venv_VV/lib/python3.12/site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in ./.venv_VV/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv_VV/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv_VV/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv_VV/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv_VV/lib/python3.12/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2024.8.30)
Using cached google_generativeai-0.8.3-py3-none-any.whl (160 kB)
Installing collected packages: google-generativeai
  Attempting uninstall: google-generativeai
    Found existing installation: google-generativeai 0.8.2
    Uninstalling google-generativeai-0.8.2:
      Successfully uninstalled google-generativeai-0.8.2
Successfully installed google-generativeai-0.8.3
